name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore DeadStart.csproj
      working-directory: .

    - name: Build
      run: dotnet build DeadStart.csproj --no-restore
      working-directory: .

    - name: Test
      run: dotnet test DeadStart.csproj --no-build --verbosity normal
      working-directory: .
